# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70640f00a802fd0cf6d2c992efaaa35ea2f8e05f1fb63638915bca345ffe5d048e0f347c90d8909c3a338a479b18704027dae40e958f13aecb9e121853f7c22d

test:
  secret_key_base: a611a17962e6b1b7330f22dccab26f960947531020d80fa98474b97b54a170d9481c3c0a0fc7952877c018cbcff7a7b5d31193a08c4995956e3b3a8bee024371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
